### ISSUE TITLE
Questions should be sorted by created day and then by importance

### ISSUE THREAD

**Issue by allkindsxyz** [AllKinds/AllkindsICP#56]
Basically the main problem here is when a new question is created - it can go somewhere in sorting so the author of a question may not see it and it's confusing. 
We need to fetch this question to top of the list so the author can see it and respond

**Comment by f0i** [comment]
The newest questions are now at the top.
This will have the side effect of users answering more newer questions which might lead to fewer common questions between users.

Including the importance of a question later should solve this problem.

**Comment by allkindsxyz** [comment]
Also when we implement NLP and geo-location features - questions should sort in a smarter way:
- by importance (which is actually popularity)
- by locations
- by particular interests of a user (recommendation system), etc.

**Comment by f0i** [comment]
I split the second part into a new issue (#61) so this one can be closed when it's tested.
