### ISSUE TITLE
Cannot answer questions when Importance is negative

### ISSUE THREAD

**Issue by allkindsxyz** [AllKinds/AllkindsICP#63]
Once Importance is negative - instead of submitting an answer it makes the importance = 0

**Comment by f0i** [comment]
Does it make sense to allow negative importance? Or is it enough to limit the number in the frontend (added in [67fe1de](https://github.com/AllKinds/AllkindsICP/commit/67fe1defdd0931e3ce6cb0d9172eee6bd8ecf240)).
Isn't this covered by the "skip" button?

**Comment by allkindsxyz** [comment]
I think it does when user doesn't consider the question important for matching, but still want to see others' answers (but it can be 0 also..)

another use case - with negative importance we can actually implement moderation system. I was thinking that while a question gets -X - it can be suspended. Also - the author of the question looses his balance (same as he gains coins when people add importance). but i think we can do think this through later
