### ISSUE TITLE
I cannot login to my existing Internet Identity account anymore

### ISSUE THREAD

**Issue by dennyweiss** [AllKinds/AllkindsICP#69]
### 📄 Summary

One month ago, I created an allkinds account with NFID based on my Internet Identity. For a while, there has been no option anymore to login with Internet Identity, nor can I use the options provided by NFID.

### ❓Quick Information

_This is to help replicate the issue as closely as possible_

Operating System: OSX 13.4, iOS current
Browser: 
- Brave (v1.57.49)
- Chrome (Version 116.0.5845.96 (Offizieller Build) (arm64))
- Safari 16.5 (18615.2.9.11.4)
- iOS Safari current

Device: iPhone, iPad, Mac
Commit: 

### 👣 Steps to reproduce

1. Open https://xroyo-niaaa-aaaal-act6a-cai.icp0.io/landing
2. Click/touch `Connect with Internet-Identity`
3. Click `Other sign in option` because Internet Identity is not listed

### 🐜 What is the current bug behavior?

1. Internet Identity is not provided as an option anymore

### ✅ What is the expected correct behavior?

1. I should be able to use `Internet Identity` because the authentication was advertised as Internet Identity, but it's NFID

### 🖼 Relevant logs or screenshots

<img width="579" alt="allkinds-ii-missing" src="https://github.com/AllKinds/AllkindsICP/assets/4938268/146014be-770f-4939-b767-2a10fb699a8e">

**Comment by dennyweiss** [comment]
@f0i @allkindsxyz was II excluded by intention?

**Comment by f0i** [comment]
@dennyweiss no, it was not excluded by intention.
There was actually no change in the AllKinds app in the last few weeks until yesterday.

The change was caused by NFID removing II and WalletConnect login options. They will add a recovery page in some weeks (see <https://twitter.com/danostrovsky/status/1693695288639201643>)

**Comment by f0i** [comment]
The new button "Log in with Internet Identity" is going directly to identity.ic0.app, which unfortunately will result in a different account than the one from the login with II via NFID.
